services:
    automiam.menu:
        class: AppBundle\Services\MenuService
        arguments: [@doctrine.orm.entity_manager]
    automiam.form.recipeselector:
        class: AppBundle\Form\RecipeSelectorType
        arguments: [@translator]
        tags:
        - { name: form.type, alias: 'appbundle_recipe_selector' }