services:
    automiam.menu:
        class: AppBundle\Services\MenuService
        arguments: [@doctrine.orm.entity_manager, @security.token_storage]
    automiam.form.recipeselector:
        class: AppBundle\Form\RecipeSelectorType
        arguments: [@translator]
        tags:
        - { name: form.type, alias: 'appbundle_recipe_selector' }
    automiam.form.recipe_exists_validator:
        class: AppBundle\Validator\Constraints\RecipeExistsValidator
        arguments: [@doctrine.orm.entity_manager, @security.token_storage]
        tags:
            - { name: validator.constraint_validator, alias: recipe_exists_validator }
    automiam.access.menu_voter:
        class:      AppBundle\Security\Authorization\Voter\MenuVoter
        public:     false
        tags:
            - { name: security.voter }
    automiam.access.recipe_voter:
        class:      AppBundle\Security\Authorization\Voter\RecipeVoter
        public:     false
        tags:
            - { name: security.voter }