<?php

namespace AppBundle\Entity;

/**
 * DayMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
