<?php

namespace AppBundle\Entity;

/**
 * MenuRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
